### ISSUE TITLE
AttributeError: 'strlist' object has no attribute 'encode'

### ISSUE THREAD

**Issue by kommen** [pdamoc/elm-docset#2]
I just tried to regenerate for Elm 0.16, but always get that error. Any pointers?

```
$ python generate.py                  
starting ...
cleanig up... DONE!
feching all packages list ... DONE!
feching new packages list ... DONE!
Traceback (most recent call last):
  File "generate.py", line 336, in <module>
    generate_all()
  File "generate.py", line 292, in generate_all
    fo.write(indexTemplate({"pkgs":[(pkg["name"], docname(pkg["name"]), pkg["summary"]) for pkg in pkgs]}))
  File "~/work/elm-docset/templates.py", line 125, in <lambda>
    indexTemplate = lambda d: pybars.Compiler().compile(index)(d, helpers={"pkglist":pkglist}).encode("utf-8")
AttributeError: 'strlist' object has no attribute 'encode'
```

**Comment by pdamoc** [comment]
Can you give me some information about your python/pybars versions? 

I have tried it on my computer with python 2.7.10 and pybars 0.9.1 and it works.

**Comment by kommen** [comment]
sure:

```
$ python --version
Python 2.7.9

$ easy_install markdown requests pybars 
Searching for markdown
Best match: Markdown 2.6.4
Processing Markdown-2.6.4-py2.7.egg
Markdown 2.6.4 is already the active version in easy-install.pth
Installing markdown_py script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages/Markdown-2.6.4-py2.7.egg
Processing dependencies for markdown
Finished processing dependencies for markdown
Searching for requests
Best match: requests 2.8.1
Processing requests-2.8.1-py2.7.egg
requests 2.8.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg
Processing dependencies for requests
Finished processing dependencies for requests
Searching for pybars
Best match: pybars 0.0.4
Processing pybars-0.0.4-py2.7.egg
pybars 0.0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages/pybars-0.0.4-py2.7.egg
Processing dependencies for pybars
Finished processing dependencies for pybars
```

**Comment by pdamoc** [comment]
Ooops, my bad... please install [pybars3](https://github.com/wbond/pybars3) and let me know if this solves it for you.

**Comment by kommen** [comment]
Works now, thank you!
